# Collector specific configuration
#TODO add details below to github secrets
url: "test"
account: "storage-account"
container: "container-name"
blob: "filename.csv"
key: "accesskey=="

dataset_names:
  WFP-MARKET-MONITORING: "wfp-market-monitoring"

allowed_tags:
  - "climate hazards"

# Metadata
start_date: "2016-10-01"
title: "WFP pipeline [Title]"
update_frequency: "monthly"
maintainer_id: "2f9fd160-2a16-49c0-89d6-0bc3230599bf"
organization_id: "75b74751-1b97-4cde-939b-1e4fb083c85c"
description: "test [Description]"
notes: "test [notes]"
